### ISSUE TITLE
why is mu_old necessary?

### ISSUE THREAD

**Issue by ypxie** [eigenfoo/batch-renorm#19]
https://github.com/eigenfoo/batch-renorm/blob/7308550aecc6ce2ae09f224c8ec24b28da2f7ecd/convnet.py#L58

why not just use
`mu_old=tf.identity(mu) ` instead of creating a variable for storing old mu?

**Comment by hexafraction** [comment]
I was @eigenfoo's partner and I wrote a lot of this code. I honestly don't recall what mu_old is used for anymore, since nothing actually reads it in the graph. It is either obsolete and unnecessary, or might have been used as an additional element for comparing mu when using `tfdbg`.

But anyway, I apologize. It's still somewhat a mess that I never really had the opportunity to clean up.

**Comment by hexafraction** [comment]
Hi there, I was @eigenfoo's partner for this academic project. I wrote a lot of this code and it's a mess, so I apologize.

To answer your question: Not 100% sure. I should be able to directly use mu in the computation of mu_add as long as the control dependencies are sequenced right. Perhaps I was working around some sort of bug, or needed these in a previous version that did something different.

**Comment by ypxie** [comment]
thanks for your reply. do you also consider correcting the bias of the moving average? @hexafraction

**Comment by hexafraction** [comment]
At the time of writing, we did not, and at the present time, we do not intend to make further changes to this repository.

**Comment by eigenfoo** [comment]
Thanks for your question @ypxie, and sorry we can't be more helpful.

Archiving this repository now.
